# development
server:
  # optional, default: 127.0.0.1
  host:
  # optional, default: 4000
  port:80
  timezone: UTC
  cluster:  false
  base_url: http://blog-ewy.herokuapp.com

db:
  db: blog-dev
  # optional, default: localhost
  host:
  # optional, default: 27017
  port:
  # optional
  username:
  # optional
  password:

cookie:
  secret: kimjkCFGyblDTk09cga93313dc222b098ujmnhFQ

session:
  # optional, default: sessions
  collection:

logs:
  - sys
  - request
  - response
  - error
  - debug

libs:

# libs that must run after server started
started:

aws:
  # your aws key & secret, those must not be empty if you set s3 option to true in assets config
  key:
  secret:
  s3:
    bucket: assets.dev.blog
